  <entry id="CVE-2013-1633">
    <vuln:vulnerable-configuration id="http://www.nist.gov/">
      <cpe-lang:logical-test negate="false" operator="OR">
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.49"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.47"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.45"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.43"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.41"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.40"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.42"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.44"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.46"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.6.48"/>
        <cpe-lang:fact-ref name="cpe:/a:python:setuptools:0.7b4"/>
      </cpe-lang:logical-test>
    </vuln:vulnerable-configuration>
    <vuln:vulnerable-software-list>
      <vuln:product>cpe:/a:python:setuptools:0.6.48</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.7b4</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.49</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.44</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.45</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.46</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.47</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.43</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.42</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.41</vuln:product>
      <vuln:product>cpe:/a:python:setuptools:0.6.40</vuln:product>
    </vuln:vulnerable-software-list>
    <vuln:cve-id>CVE-2013-1633</vuln:cve-id>
    <vuln:published-datetime>2013-08-05T22:52:10.333-04:00</vuln:published-datetime>
    <vuln:last-modified-datetime>2013-10-11T09:59:05.830-04:00</vuln:last-modified-datetime>
    <vuln:cvss>
      <cvss:base_metrics>
        <cvss:score>6.8</cvss:score>
        <cvss:access-vector>NETWORK</cvss:access-vector>
        <cvss:access-complexity>MEDIUM</cvss:access-complexity>
        <cvss:authentication>NONE</cvss:authentication>
        <cvss:confidentiality-impact>PARTIAL</cvss:confidentiality-impact>
        <cvss:integrity-impact>PARTIAL</cvss:integrity-impact>
        <cvss:availability-impact>PARTIAL</cvss:availability-impact>
        <cvss:source>http://nvd.nist.gov</cvss:source>
        <cvss:generated-on-datetime>2013-08-05T04:39:54.000-04:00</cvss:generated-on-datetime>
      </cvss:base_metrics>
    </vuln:cvss>
    <vuln:cwe id="CWE-20"/>
    <vuln:references xml:lang="en" reference_type="VENDOR_ADVISORY">
      <vuln:source>CONFIRM</vuln:source>
      <vuln:reference href="https://pypi.python.org/pypi/setuptools/0.9.8#changes" xml:lang="en">https://pypi.python.org/pypi/setuptools/0.9.8#changes</vuln:reference>
    </vuln:references>
    <vuln:references xml:lang="en" reference_type="UNKNOWN">
      <vuln:source>MISC</vuln:source>
      <vuln:reference href="http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/" xml:lang="en">http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/</vuln:reference>
    </vuln:references>
    <vuln:summary>easy_install in setuptools before 0.7 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to the default use of the product.</vuln:summary>
  </entry>
